language: node_js
node_js:
        - "0.12"
services:
        - mongodb
before_script:
        - mongo appDB --eval 'db.addUser("liudan", "shimiao");'
        - npm install -g mocha
script: cd test && mocha

