language: node_js
node_js:
        - "0.12"
services:
        - mongodb
before_script:
        - mongo appDB --eval 'db.addUser("cornell", "tech");'
        - npm install -g mocha
script: cd test && mocha

